### ISSUE TITLE
[TASK] Add TestNet/MainNet application binary

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/gadget#73] opened 2024-02-15 15:20 UTC
The gadget repo uses multiple protocols, and inside each of these protocols, we have unit tests that create a `NodeInput` struct that contains a `MockNetwork`, a `MockPalletSubmitter`, and a `MockClient` in order to construct a node capable of running multiple relevant protocols simultaneously.

To go from these unit tests to an actual application that interacts with the testnet (or mainnet), we need to apply a similar approach to these tests, except using a `GossipNetwork`, `SubxtPalletSubmitter`, and a `SubstrateClient` as inputs inside the `NodeInput` struct instead. Note: for zk-saas, the network implementation will differ. Therefore, the network implementation should continue to remain general when writing an `ApplicationBuilder` abstraction that allows us to quickly write nodes. The `ApplicationBuilder` will always use the `SubxtPalletSubmitter` and `SubstrateClient`, but, will expect a generic `Network` input as well as any relevant variables that are required to construct the `SubxtPalletSubmitter` and the `SubstrateClient`. This approach will allow us to target testnet/mainnet with a mere config file. Thus, ideally, application binaries that use different protocols will be composable via config files.

**Comment by shekohex** [comment] 2024-02-19 10:54
I will work on adding support for `SubxtPalletSubmitter` implementation.

**Comment by shekohex** [comment] 2024-02-19 17:38
Working on updating the [`GossipNetwork`](https://github.com/webb-tools/gadget/blob/main/gadget-common/src/gadget/network/gossip.rs) and ensure it is up-to-date and working.

**Comment by shekohex** [comment] 2024-03-19 08:56
Duplicate of #91

**Closed by shekohex** 2024-03-19 08:56 UTC
Labels: feature ➕
